### ISSUE TITLE
parsing of line labels in Format

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18#180]
Format is declared as
struct Format {
  UNION_CLASS_BOILERPLATE(Format);
  std::variant<DefaultCharExpr, Label, Star> u;
};

With an input such as 
  write (*,60) "Hello, World"
60 format (A)
  end

It appears that the parser is returning a Format that holds IntLiteralConstant->LiteralConstant with the value 60 rather than a Label 60.

**Comment by klausler** [comment]
A `Format` can't hold an `IntLiteralConstant`.  Where are you encountering the `IntLiteralConstant`?

**Comment by klausler** [comment]
I see.  In `lib/parser/grammar.h`, try rearranging the alternatives for Format (R1215) so that `label` is attempted before defaultCharExpr, not after.  Since parsing isn't sensitive to semantic information, the parser is most likely recognizing a label number as a valid expression (which it is) and treating it as an expression that must later be checked to be CHARACTER in semantics.

Ignore this comment if you prefer me to resolve this later or if you don't need an immediate fix.

**Comment by klausler** [comment]
The tweak needs to be made in `grammar.h`, not `parse-tree.h`, and I'll get on it tomorrow.

**Comment by klausler** [comment]
I think that this issue can now be closed; please do so at your convenience if you agree.  Thanks for your help on this.

**Comment by schweitzpgi** [comment]
Fixed (for me).
