### ISSUE TITLE
About F18 integration with LLVM (**Query**)

### ISSUE THREAD

**Issue by hcltrajesh** [flang-compiler/f18#300]
Hello,

This is in continuation to my query, logged as issue #290.
I have some more queries (these are not issues) about f18:
1. Is there any tentative timeline by which f18 would be integrated with LLVM? As we know, the f18 currently uses PG Fortran for compilation of a program.
2. Is there any other dedicated forum/distribution list etc. where we can get all the latest information/update about work being done in f18?

Regards.

**Comment by sscalpone** [comment]
The use of PGI Fortran to compile programs is purely for testing.  I predict that f18 will start to generate llvm ir in May 2019.

We have mailing lists for announcements and developers. Here's the link with the sign-up information:
http://lists.flang-compiler.org/mailman/listinfo

We have a flang-compiler channel on Slack. Slack is invitation only but anyone can join. Here's the link:
https://join.slack.com/t/flang-compiler/shared_invite/MjExOTEyMzQ3MjIxLTE0OTk4NzQyNzUtODQzZWEyMjkwYw

**Comment by sscalpone** [comment]
@hcltrajesh OK to close this issue?

**Comment by sscalpone** [comment]
Hi @hcltrajesh, please reopen this issue if you have more questions.

**Comment by ggouaillardet** [comment]
`f18` is getting a lot of traction following the announcement  as a `LLVM` project.

I would suggest you update the `README.md` in order to clearly describes the current status (long story short, an external fortran compiler is required, it is `pgf90` by default and that can be changed by setting the `F18_FC` environment variable) and the plan (no more need for an external fortran compiler).
