### ISSUE TITLE
Internal error on DO loop index

### ISSUE THREAD

**Issue by klausler** [flang-compiler/f18#518]
```
  do 1 j=1,2
    if (.true.) then
1   end if
  end
```

elicits a legitimate error message about the label `1` but also emits `error: Internal: no symbol found for 'j'` when semantics is enabled.

**Comment by jeanPerier** [comment]
**First analysis:**
`LabelDoStmt` are supposed to be rewritten to `NonLabelDoStmt` by label resolution before name resolution.
Name resolution forbids name resolution inside `LabelDoStmt` on purpose (see  [resolve-names.cc L918](https://github.com/flang-compiler/f18/blob/248600031d8fc500edc3e97e8921a0bad64681de/lib/semantics/resolve-names.cc#L918)) (because it does not expect them ?).

The `label '1' is not in scope` is not emitted as an error but warning. This is in line with other compilers (e.g pgfortran) that accepts the construct. However, label resolution failed to rewrite the `LabelDoStmt` to `NonLabelDoStmt` in this situation. Hence, `j` is not resolved and error message emitted.

**Planned follow-up:**
- See why label resolution failed to rewrite the `LabelDoStmt` to `NonLabelDoStmt`
- either fix it if possible, or stop guaranteeing the absence of `LabelDoStmt` in later stages

**Comment by jeanPerier** [comment]
@klausler do you confirm it is solved ?

**Comment by jeanPerier** [comment]
Fixed by #553: Code from issue compiles without errors.
Note that `Document issue #518 workaround` commit 9bd5ad9 linked in this issue has a wrong title, it is about issue #527 workaround. No workaround were needed for the issue at hand.
