### ISSUE TITLE
Extension "ordering of component declarations"

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18#618]
b-test.f90:4:14: error: type parameter definitions must appear before component declarations
 integer, kind :: k = 4
               ^

module m
type :: b(k,c,r)
  private
    integer, kind :: k = 4
    integer, len :: c = 1
    integer, len :: r = 1
end
end

**Comment by klausler** [comment]
The message is not incorrect with respect to the Fortran standard.  See 7.5.2.1.  pgfortran allows type parameter definitions to appear anywhere in a derived type definition because it treats type parameters like components in many ways.  The standard requires type parameter definitions to come before anything else in a derived type, including `private`.

**Comment by sscalpone** [comment]
Allowed in ifort.  Disallowed in xlf.

**Comment by klausler** [comment]
Having a type parameter definition follow `private` is problematic if it would imply that the type parameter name would truly be inaccessible outside the type.  Maybe ifort allows the usage but doesn't actually make the parameter's name private; just speculating.  Anyway, I am skeptical that this is something that we need or want to support -- it would be nontrivial to handle in the parser and parse tree, and any program that violates this rule can be fixed easily.
