### ISSUE TITLE
Possible undefined behaviour

### ISSUE THREAD

**Issue by peterwaller-arm** [flang-compiler/f18#747]
@klausler hi! :wave:.

I was going through the commits and noticed #666 / 34a917c761541d7325156baafab47966264f2a3c (clean up warnings) in this use of a union. I wonder if it is undefined behaviour according to the standard. I understand that you're only allowed to access the member of a union that was most recently assigned to.

In practice the compilers we currently support may not do anything which breaks this code, but I wanted to just query what the project's stance is on the use of undefined behaviour like this.

https://github.com/flang-compiler/f18/blob/2752d09c3a7f599c27de14fcef3846f9db39e97e/lib/evaluate/intrinsics-library-templates.h#L132-L146

The alternative seems to be to use `reinterpret_cast<>`, which I see the patch moved away from. The standard does appear to allow such conversion of function pointers, so long as "you put them back how you found them before you call them" from C++ standard [5.2.10 Reinterpret cast paragraph 6](http://eel.is/c++draft/expr.reinterpret.cast#6):

> A function pointer can be explicitly converted to a function pointer of a different type. The effect of calling a function through a pointer to a function type (8.3.5) that is not the same as the type used in the definition of the function is undefined. Except that converting a prvalue of type “pointer to T1” to the type “pointer to T2” (where T1 and T2 are function types) and back to its original type yields the original pointer value, the result of such a pointer conversion is unspecified.

/cc @DavidTruby

**Comment by klausler** [comment]
I couldn't get a clean warning-free compilation out of all of the various versions of the several compilers with which I test builds when I was using`reinterpret_cast<>`.  So I used (or reverted to using?  don't remember) a `union` so that it would be painfully obvious to all that I'm working around the type system.  It is of course undefined behavio(u)r.  ("Sin boldly!")  I decided that it was worth the UB to be able to compile f18 with all compiler warnings enabled with all compilers.

You are invited to try to do better.  I would of course prefer using `reinterpret_cast<>` over any of the many other ways of implementing a generic polymorphic function pointer in C++ with all warnings enabled; but even the old trick of using multiple casts and an integral intermediate type didn't work.  Modern C++ intentionally and properly makes this difficult thing to do.

**Comment by klausler** [comment]
May we close this bug?

**Comment by DavidTruby** [comment]
I'd like to have a look at this, I feel like there must be a way for us to avoid both warnings and undefined behaviour, even if the UB is safe on all the compilers we currently support. Do you have any info about which compilers issued warnings for the old way of doing it?

**Comment by DavidTruby** [comment]
So this was from a warning added in GCC8 (-wcast-function-type). It seems that you can bypass the warning by _specifically_ casting to and from the type `void (*) (void)`. Previously we were casting to/from `void (*) ()` (which... should be exactly the same type in C++? I find this confusing.)

If I change GenericFunctionPointer to be `void (*) (void)` and reinterpret_cast to/from that, I can compile on gcc 8 and 9 with no warnings and no UB :smile:

**Comment by klausler** [comment]
I'll test all the other environments that we use.

**Comment by DavidTruby** [comment]
I had a go at fixing this in a nicer way using `std::any`, and it seems like we're not always casting back to the same function type we originally came from. I've verified this to be the case with both the original access through union code and the `reinterpret_cast` code in my PR using clang's undefined behavior sanitizer, which has a check for calling through function pointers of the incorrect type.

This is more of an issue than the original `union` UB because this is actual UB that compilers do optimize on the assumption it doesn't happen (unlike the union case which is allowed by most compilers).

Here is an example of one of the errors that the UBSan in clang throws:
```
actual at 215: runtime error: call to function Fortran::evaluate::CallableHostWrapper<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>, Fortran::evaluate::ArgumentInfo<Fortran::evaluate::Type<(Fortran::common::TypeCategory)1, 4>, (Fortran::evaluate::PassBy)1> >::scalarCallable(Fortran::evaluate::FoldingContext&, float (*)(float), Fortran::evaluate::value::Real<Fortran::evaluate::value::Integer<32, true, 32, unsigned int, unsigned long>, 24, true> const&) through pointer to incorrect function type 'Fortran::evaluate::value::Real<Integer<32>, 24> (*)(Fortran::evaluate::FoldingContext &, void *(*)(), const Fortran::evaluate::value::Real<Integer<32>, 24> &)'
```

I'll see if I can get to the bottom of the issue.
