### ISSUE TITLE
Assignment between incompatible structure types allowed

### ISSUE THREAD

**Issue by psteinfeld** [flang-compiler/f18#799]
When I create variables of different structure types that inherit from the same type, f18 allows it without error.  GNU, ifort, and xlf all produce error messages.
[bug.f90.txt](https://github.com/flang-compiler/f18/files/3784745/bug.f90.txt)

**Comment by klausler** [comment]
We haven't implemented semantic checking for assignments yet.

**Comment by hcltrajesh** [comment]
i hope, this issue is fixed as per sources downloaded on 30-Nov-2019.
I could confirm the case bug.f90 as attached above. 
Appropriate error message is being generated now. 
ii.f90:19:3: error: No intrinsic or user-defined ASSIGNMENT(=) matches operand types TYPE(base) and TYPE(a)
-------------------------
    baseVar = aVar
    ^^^^^^^^^^^^^^
ii.f90:20:3: error: No intrinsic or user-defined ASSIGNMENT(=) matches operand types TYPE(b) and TYPE(a)
    bVar = aVar
    ^^^^^^^^^^^
------------------
Shouldn't this issue be marked as CLOSED?

**Comment by psteinfeld** [comment]
> 
> 
> i hope, this issue is fixed as per sources downloaded on 30-Nov-2019.
> I could confirm the case bug.f90 as attached above.
> Appropriate error message is being generated now.
> ii.f90:19:3: error: No intrinsic or user-defined ASSIGNMENT(=) matches operand types TYPE(base) and TYPE(a)
> ii.f90:19:3: error: No intrinsic or user-defined ASSIGNMENT(=) matches operand types TYPE(base) and TYPE(a)
> baseVar = aVar
> ^^^^^^^^^^^^^^
> ii.f90:20:3: error: No intrinsic or user-defined ASSIGNMENT(=) matches operand types TYPE(b) and TYPE(a)
> bVar = aVar
> ^^^^^^^^^^^
> 
> Shouldn't this issue be marked as CLOSED?

Thanks, @hcltrajesh .  I verified this, too.
